name: attendancewithfingerprint
description: A application for attendance with fingerprint.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  sqflite: ^2.2.0
  path_provider: ^2.0.15
  barcode_scan2: ^4.2.0 # Updated fork of barcode_scan
  font_awesome_flutter: ^10.5.0
  intl: ^0.19.0
  geolocator: ^13.0.2
  flutter_easyloading: ^3.0.5 # Null-safe replacement for progress_dialog
  dio: ^5.2.1
  flutter_launcher_icons: ^0.14.2
  rflutter_alert: ^2.0.4
  permission_handler: ^11.3.1
  android_intent_plus: ^5.2.0 # Updated fork of android_intent
  shared_preferences: ^2.2.0
  local_auth: ^2.1.5
  change_app_package_name: ^1.1.0
  sn_progress_dialog: ^1.1.4
  trust_location: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

